#!/bin/bash
VPS=$1
if [ -z ${VPS} ];
then
    printf "Error: VMID missing/undefined\n";
    printf "Usage: vzspeed VMID";
    exit
fi
printf "Displaying Network usage for VMID: $VPS \n";
while true
do
  R1=`/usr/sbin/vzctl exec $VPS cat /sys/class/net/venet0/statistics/rx_bytes`
  T1=`/usr/sbin/vzctl exec $VPS cat /sys/class/net/venet0/statistics/tx_bytes`
  sleep 1
  R2=`/usr/sbin/vzctl exec $VPS cat /sys/class/net/venet0/statistics/rx_bytes`
  T2=`/usr/sbin/vzctl exec $VPS cat /sys/class/net/venet0/statistics/tx_bytes`
  TBPS=`expr $T2 - $T1`
  RBPS=`expr $R2 - $R1`
  TKBPS=`expr $TBPS / 1024`
  RKBPS=`expr $RBPS / 1024`
  echo "TX: $TKBPS kB/s | RX: $RKBPS kB/s"
done
